spring:
  application:
    name: grafana-test
management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
    build:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      all: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: grafana-test
  endpoint:
    health:
      show-details: always
  server:
    port: 8081
